alias ll='ls -laoh --color=auto'
alias be='bundle exec'
alias df='df -h'
alias rm='rm -iv'
alias cp='cp -iv'
alias mv='mv -iv'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias amend='git commit --amend -C HEAD'
alias log='git log --pretty="format:%C(yellow)%h%C(green)%d %C(white)%s %C(cyan)%an, %ar %Creset"'
alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'
alias size='du -sh'
alias chrome='google-chrome --cipher-suite-blacklist=0x0004,0x0005,0xc01'
alias google-chrome='google-chrome --cipher-suite-blacklist=0x0004,0x0005,0xc01'
alias tree='tree -C'
