alias ll='ls -laoh'
alias be='bundle exec'
alias df='df -h'
alias rm='rm -iv'
alias cp='cp -iv'
alias mv='mv -iv'
alias log='git log --pretty="format:%C(yellow)%h%C(green)%d %C(white)%s %C(cyan)%an, %ar %Creset"'
alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'
alias size='du -sh'
