export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8
export TERM=xterm-256color
export PS1='[\u@\h \W]\$ '
export EDITOR=vim
export HISTSIZE=2000
export NPM_HOME=$HOME/npm
export PATH=$HOME/node_modules/.bin:$HOME/bin:$PATH
